# Generated by Django 2.0 on 2019-03-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driver_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle'),
        ),
    ]
