# Generated by Django 2.0 on 2019-03-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DeliveryCompany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitue', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('delivery_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryCompany.DeliveryCompany')),
            ],
        ),
    ]
