# Generated by Django 2.0 on 2019-03-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='latitue',
            new_name='latitude',
        ),
    ]
