# Generated by Django 2.0 on 2019-03-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20190315_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
    ]
