# Generated by Django 2.0 on 2019-03-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_vehicle_tracked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='latitude',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='longitude',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
